# Generated by Django 4.2 on 2023-12-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[(1, "Male"), (2, "Female")], default=0, max_length=10
            ),
        ),
    ]
