# Generated by Django 4.2 on 2023-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0002_pet_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[(1, "Male"), (2, "Female")], default=2, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[(1, "Dog"), (2, "Cat"), (3, "Bird"), (4, "Fish")],
                default=1,
                max_length=10,
            ),
        ),
    ]
