# Generated by Django 4.2 on 2023-12-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0009_alter_vet_clinic_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vet",
            name="clinic_hours",
            field=models.DateTimeField(blank=True, default=0),
        ),
    ]
