# Generated by Django 4.2 on 2023-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0010_alter_vet_clinic_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.AddField(
            model_name="pet",
            name="color",
            field=models.CharField(default="", max_length=20),
        ),
    ]
