# Generated by Django 4.2 on 2023-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0011_remove_client_name_pet_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
