# Generated by Django 4.2 on 2023-12-14 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0012_client_first_name_client_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="appointments",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vet",
            name="clinic_hours",
            field=models.DurationField(blank=True, default=0),
        ),
    ]
